# Generated by Django 5.2.8 on 2025-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buy_code', models.IntegerField(primary_key=True, serialize=False)),
                ('buy_name', models.CharField(max_length=12)),
                ('staff_code', models.IntegerField()),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
    ]
